/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mc;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.MouseInputListener;

/**
 *
 * @author ASUS
 */
public class AdminLogIn extends javax.swing.JFrame implements MouseInputListener{
    int x, y, xx, yy;
    JLabel label5, a, label6, label7, b;
    /**
     * Creates new form AdminLogIn
     */
    public AdminLogIn() {
        initComponents();
        
        label5 = new JLabel();
        label5.setBounds(5, 6, 15, 15);
        ImageIcon icon5 = new ImageIcon("src/mc/assests/cross.png");
        Image img5 = icon5.getImage();
        Image imgScale5 = img5.getScaledInstance(label5.getWidth(), label5.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon5 = new ImageIcon(imgScale5);
        label5.setIcon(scaledIcon5);
        label5.addMouseListener(this);
        pan.add(label5);
        
        a = new JLabel();
        a.setBounds(5, 6, 15, 15);
        ImageIcon icon9 = new ImageIcon("src/mc/assests/cross1.png");
        Image img9 = icon9.getImage();
        Image imgScale9 = img9.getScaledInstance(a.getWidth(), a.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon9 = new ImageIcon(imgScale9);
        a.setIcon(scaledIcon9);
        a.addMouseListener(this);
        pan.add(a);
        
        label6 = new JLabel();
        label6.setBounds(25, 6, 15, 15);
        label6.addMouseListener(this);
        ImageIcon icon6 = new ImageIcon("src/mc/assests/expand.png");
        Image img6 = icon6.getImage();
        Image imgScale6 = img6.getScaledInstance(label6.getWidth(), label6.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon6 = new ImageIcon(imgScale6);
        label6.setIcon(scaledIcon6);
        pan.add(label6);
        
        label7 = new JLabel();
        label7.setBounds(45, 6, 15, 15);
        label7.addMouseListener(this);
        ImageIcon icon7 = new ImageIcon("src/mc/assests/minus.png");
        Image img7 = icon7.getImage();
        Image imgScale7 = img7.getScaledInstance(label7.getWidth(), label7.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon7 = new ImageIcon(imgScale7);
        label7.setIcon(scaledIcon7);
        pan.add(label7);
        
        b = new JLabel();
        b.setBounds(45, 6, 15, 15);
        b.addMouseListener(this);
        ImageIcon icon8 = new ImageIcon("src/mc/assests/minus1.png");
        Image img8 = icon8.getImage();
        Image imgScale8 = img8.getScaledInstance(b.getWidth(), b.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon8 = new ImageIcon(imgScale8);
        b.setIcon(scaledIcon8);
        pan.add(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pan = new keeptoo.KGradientPanel();
        kButton4 = new com.k33ptoo.components.KButton();
        jLabel4 = new javax.swing.JLabel();
        kButton3 = new com.k33ptoo.components.KButton();
        Lock1 = new javax.swing.JLabel();
        idField = new textfield.TextField();
        passField = new passfield.PassField();

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan.setkEndColor(new java.awt.Color(52, 73, 94));
        pan.setkGradientFocus(0);
        pan.setkStartColor(new java.awt.Color(23, 32, 42));
        pan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panMouseDragged(evt);
            }
        });
        pan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panLayout = new javax.swing.GroupLayout(pan);
        pan.setLayout(panLayout);
        panLayout.setHorizontalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        panLayout.setVerticalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        jPanel1.add(pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        kButton4.setBorder(null);
        kButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/assests/go_back3.png"))); // NOI18N
        kButton4.setText("Go Back");
        kButton4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        kButton4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        kButton4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        kButton4.setkBorderRadius(20);
        kButton4.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton4.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton4.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton4.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton4.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton4.setkStartColor(new java.awt.Color(255, 255, 255));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 595, 120, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/assests/logo.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        kButton3.setBorder(null);
        kButton3.setText("Sign In");
        kButton3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        kButton3.setkBorderRadius(20);
        kButton3.setkEndColor(new java.awt.Color(233, 228, 240));
        kButton3.setkForeGround(new java.awt.Color(51, 51, 51));
        kButton3.setkHoverEndColor(new java.awt.Color(211, 204, 227));
        kButton3.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        kButton3.setkHoverStartColor(new java.awt.Color(233, 228, 240));
        kButton3.setkStartColor(new java.awt.Color(211, 204, 227));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 90, 30));

        Lock1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/assests/lock2.png"))); // NOI18N
        jPanel1.add(Lock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        idField.lineColor = new Color(255,255,255);
        idField.setBackground(new java.awt.Color(0, 0, 51));
        idField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        idField.setForeground(new java.awt.Color(255, 255, 255));
        idField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idField.setLabelText("ID");
        idField.setLineColor(new java.awt.Color(255, 255, 255));
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });
        jPanel1.add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 250, 50));

        passField.lineColor = new Color(255,255,255);
        passField.setBackground(new java.awt.Color(0, 0, 51));
        passField.setEchoChar('\u25CF');
        passField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        passField.setForeground(new java.awt.Color(255, 255, 255));
        passField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passField.setLabelText("Passcode");
        passField.setLineColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 250, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panMouseDragged
        x = evt.getXOnScreen();
        y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_panMouseDragged

    private void panMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_panMousePressed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        HomePage hm = new HomePage();
        hm.setVisible(true);
        hm.setLocation(this.getX(), this.getY());
        dispose();
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        String id = idField.getText();
        String pass = passField.getText();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/quizhub", "root", "connected");
            Statement st = con.createStatement();
            String query = "select * from admin where ID='"+id+"' and Password='"+pass+"'";
            ResultSet rs = st.executeQuery(query);
            if(rs.next()){
                AdminPage ap = new AdminPage();
                ap.setVisible(true);
                ap.setLocation(this.getX(), this.getY());
                dispose();
            }
            else JOptionPane.showMessageDialog(null, "Incorrect username and password...");
            con.close();
        }
        catch(ClassNotFoundException | SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_kButton3ActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lock1;
    private textfield.TextField idField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton4;
    private keeptoo.KGradientPanel pan;
    private passfield.PassField passField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        if(e.getSource() == a){
            System.exit(0);
        }
        if(e.getSource() == b){
            this.setState(this.ICONIFIED);
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        if(e.getSource() == label5) {
            label5.setVisible(false);
            a.setVisible(true);
            a.setCursor(new Cursor(Cursor.HAND_CURSOR));
	}
	if(e.getSource() == label7) {
            label7.setVisible(false);
            b.setVisible(true);
            b.setCursor(new Cursor(Cursor.HAND_CURSOR));
	}
    }

    @Override
    public void mouseExited(MouseEvent e) {
        if(e.getSource() == a) {
            a.setVisible(false);
            label5.setVisible(true);
            label5.setCursor(new Cursor(Cursor.HAND_CURSOR));
	}
	if(e.getSource() == b) {
            b.setVisible(false);
            label7.setVisible(true);
            label7.setCursor(new Cursor(Cursor.HAND_CURSOR));
	}
    }

    @Override
    public void mouseDragged(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseMoved(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
